### ISSUE TITLE
Sometimes it deletes more than 1 action

### ISSUE THREAD

**Issue by salahmak** [iMrDJAi/UndoRedo.js#1]
I liked the package, it is pretty cool, but when testing it sometimes it reverts more than 2 actions.
ik u can fix it fast. Keep up the good work dude :)

**Comment by iMrDJAi** [comment]
U mean when you undo it does it twice?

**Comment by iMrDJAi** [comment]
I will close this one, I'm gonna talk with you in chat bro!
